server:
  port: 8762
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cashierdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Bloodline1314..
  application:
      name: provider
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml